# Generated by Django 5.1.1 on 2024-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
