# Generated by Django 5.1.1 on 2024-10-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_category_employee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
